#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>"/dev/null" || \
source \
  "${_crash_bash}"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    "node-run"
  _check_cmd \
    'serve' \
    "nodejs-serve"
  _check_cmd \
    "openssl"
}

# shellcheck disable=SC2034
_global_variables() {
  run_date=""
  target_environment=""
  target_message=""
  target_planet=""
  cache_dir=""
  color=""
  quiet=""
}

_cert_new() {
  local \
    _key_file="${1}" \
    _cert_file="${2}" \
    _openssl_opts=()
  _openssl_opts+=(
    -x509
    -newkey
      "rsa:4096"
    -keyout
      "key.pem"
    -out
      "cert.pem"
    -sha256
    -days
      3650
    -nodes
    -subj
    "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
  )
  openssl \
    req \
    "${_openssl_opts[@]}"
}

_cert_setup() {
  local \
    _key_file \
    _cert_file
  _key_file="${_cache_dir}/key.pem"
  _cert_file="${_cache_dir}/cert.pem"
  _cert_new \
    "${_key_file}" \
    "${_cert_file}"
  _serve_opts+=(
    --ssl-cert
      "${_cert_file}"
  )
}

# Hello world application
# $1: target environment (browser or node)
# $2: salutation message
# $3: target planet
_ahsi() {
  local \
    _target_environment="${1}" \
    _target_message="${2}" \
    _target_planet="${3}" \
    _cache_dir="${4}" \
    _opts=() \
    _node_run_opts=() \
    _serve_opts=() \
    _serve_cfg \
    _cmd_path \
    _cmd=() \
    _usr \
    _oldpwd \
    _msg=()
  _usr="$(
    _get_usr)"
  _app_dir="${_usr}/lib/${app_name}"
  _serve_cfg="${_app_dir}/serve.json"
  _cert_setup
  if [[ "${quiet}" == "n" ]]; then
    _node_run_opts+=(
      -v
    )
  fi
  _oldpwd="${PWD}"
  if [[ "${_target_environment}" == "node" ]]; then
    _cmd_path="${_app_dir}/${app_name}"
    node-run \
      "${_node_run_opts[@]}" \
      "${_cmd_path}"
  elif [[ "${_target_environment}" == "browser" ]]; then
    _serve_opts+=(
      --config
        "${_serve_cfg}"
    )
    _msg=(
      "Running serve with options"
      "'${_serve_opts[*]}'."
    )
    _msg_info \
      "${_msg[*]}"
    _cmd=(
      cd
        "${_app_dir}" "&&"
      serve
        "${_serve_opts[@]}"
	"${_app_dir}" "&&"
      cd
        "${_oldpwd}"
    )
    bash \
      -c \
        "${_cmd[*]}"
  fi
  cd \
    "${_oldpwd}"
}

_cache_dir_auto_detect() {
  local \
    _cache_dir
  _cache_dir="${HOME}/.cache/${app_name}"
  if [[ ! -v "override_cache_dir" ]]; then
    if [[ ! -d "${_cache_dir}" ]]; then
      mkdir \
        -p \
	"${_cache_dir}"
      chmod \
        700 \
	"${_cache_dir}"
    fi
  fi
  _set_override \
    "cache" \
    "dir" \
    "${_cache_dir}"
}

# Set defaults and, if present, overrides
# from arch-grub command line option parameters
_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "run" \
    "date" \
    "$(_get_date_human)"
  if [[ "${target_planet}" == "" ]]; then
    target_planet="venus"
  fi
  if [[ ! -v "override_target_environment" ]]; then
    target_environment="node"
  else
    target_environment="${override_target_environment}"
  fi
  _cache_dir_auto_detect
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                       Run date:   ${run_date}"
  _msg_info "             Target environment:   ${target_environment}"
  _msg_info "                 Target message:   ${target_message}"
  _msg_info "                  Target planet:   ${target_planet}"
  _msg_info "          Application options:"
  _msg_info "                Cache directory:   ${cache_dir}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage
  IFS='' \
    read \
      -r \
      -d '' \
      _usage << \
        ENDUSAGETEXT || true

Hello world for a program using the Crash Bash and the Crash Javascript libraries together.

Usage:

  ${app_name}
    [options]
    <message>
    <world>

  arguments:
    message               Hello to send.
    planet                Optional, planet to send the message.
                          Default: ${target_planet}

  options:
     -p <environment>     It can be 'browser' or
                          'node'.
                          Default: ${target_environment}
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage}"
  exit \
    "${_exit}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
_getopts='p:cvh?'
while \
  getopts \
    "${_getopts}" \
    arg; do
  case \
    "${arg}" in
    p)
      override_target_environment="${OPTARG}" ;;
    W)
      override_cache_dir="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides && \
      _usage \
        1 ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( ${#} < 1 )); then
  _msg=(
    "Message required."
  )
  _set_overrides
  _msg_error \
    "${_msg[*]}" \
    0
  _usage \
    1
fi
target_message="${1}"
if (( 1 < ${#} )); then
  target_planet="${2}"
fi
_set_overrides
_show_config
app_opts=(
  "${target_environment}"
  "${target_message}"
  "${target_planet}"
  "${cache_dir}"
)
_ahsi \
  "${app_opts[@]}"
